import os
import torch
import cv2
import numpy as np
from PIL import Image
from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection
from tqdm import tqdm

def generate_yaml(classes, yaml_path="dataset.yaml"):
    """Automatically generates the dataset.yaml file for YOLO."""
    names_dict = {i: name.replace(" ", "_") for i, name in enumerate(classes)}
    
    yaml_content = f"""# Auto-generated by V2 Pipeline
path: data/dataset 
train: train/images
val: val/images

names:
"""
    for k, v in names_dict.items():
        yaml_content += f"  {k}: {v}\n"
        
    with open(yaml_path, "w") as f:
        f.write(yaml_content)
    print(f"--> Automatically generated {yaml_path} with classes: {names_dict}")
    return names_dict

def main():
    # --- USER INPUT SECTION ---
    # Just type what you want to find here. The script handles the rest.
    TARGET_CLASSES = ["steel water bottle", "person"]  # Add more classes as needed
    CONFIDENCE_THRESHOLD = 0.35
    
    # --- PATH SETUP ---
    IMAGE_DIR = "data/extracted_frames"
    LABEL_DIR = "data/labels"
    PROOF_DIR = "data/visual_proof"
    
    os.makedirs(LABEL_DIR, exist_ok=True)
    os.makedirs(PROOF_DIR, exist_ok=True)

    # 1. Generate YAML and Class Maps
    class_map = generate_yaml(TARGET_CLASSES)
    # Format for DINO: "class1 . class2 . class3 ."
    dino_prompt = " . ".join(TARGET_CLASSES) + " ." 
    
    # 2. Load Model
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"\nLoading Grounding DINO on: {device.upper()}...")
    model_id = "IDEA-Research/grounding-dino-base"
    processor = AutoProcessor.from_pretrained(model_id)
    model = AutoModelForZeroShotObjectDetection.from_pretrained(model_id).to(device)

    # 3. Process Images
    image_files = [f for f in os.listdir(IMAGE_DIR) if f.lower().endswith((".jpg", ".png"))]
    print(f"Starting V2 Auto-Annotation & Visual Proofing for {len(image_files)} images...")
    
    for img_name in tqdm(image_files, desc="Processing"):
        img_path = os.path.join(IMAGE_DIR, img_name)
        
        # Load for DINO (PIL RGB) and OpenCV (BGR for drawing)
        pil_image = Image.open(img_path).convert("RGB")
        cv2_image = cv2.imread(img_path)
        img_width, img_height = pil_image.size

        # Run DINO
        inputs = processor(images=pil_image, text=dino_prompt, return_tensors="pt").to(device)
        with torch.no_grad():
            outputs = model(**inputs)

        results = processor.post_process_grounded_object_detection(
            outputs,
            inputs.input_ids,
            threshold=CONFIDENCE_THRESHOLD,
            target_sizes=[pil_image.size[::-1]]
        )[0]

        # Prepare text file
        label_path = os.path.join(LABEL_DIR, os.path.splitext(img_name)[0] + ".txt")
        
        with open(label_path, "w") as f:
            for score, label_str, box in zip(results["scores"], results["labels"], results["boxes"]):
                # Map DINO's string output back to our integer ID
                class_id = -1
                for idx, target in enumerate(TARGET_CLASSES):
                    if target.lower() in label_str.lower():
                        class_id = idx
                        break
                
                if class_id == -1:
                    continue # Skip if DINO hallucinates a weird label

                # YOLO Format Conversion
                xmin, ymin, xmax, ymax = box.tolist()
                x_center = max(0, min(1, ((xmin + xmax) / 2) / img_width))
                y_center = max(0, min(1, ((ymin + ymax) / 2) / img_height))
                box_width = max(0, min(1, (xmax - xmin) / img_width))
                box_height = max(0, min(1, (ymax - ymin) / img_height))

                f.write(f"{class_id} {x_center:.6f} {y_center:.6f} {box_width:.6f} {box_height:.6f}\n")

                # --- VISUAL PROOF DRAWING ---
                conf = score.item()
                color = (0, 255, 0) # Green box
                cv2.rectangle(cv2_image, (int(xmin), int(ymin)), (int(xmax), int(ymax)), color, 2)
                
                label_text = f"{class_map[class_id]} {conf:.2f}"
                cv2.putText(cv2_image, label_text, (int(xmin), int(ymin)-10), 
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

        # Save Visual Proof
        proof_path = os.path.join(PROOF_DIR, img_name)
        cv2.imwrite(proof_path, cv2_image)

    print(f"\nSuccess! Visual proofs saved to: {PROOF_DIR}")
    print(f"YAML automatically updated at: dataset.yaml")

if __name__ == "__main__":
    main()